

import { 
  AlertTriangle, 
  Printer, 
  X, 
  CheckCircle, 
  Activity,
  Maximize2,
  XCircle,
  EyeOff,
  Eye,
  ZoomIn,
  ZoomOut,
  ArrowUp,
  Waves, // For Smears
  GripHorizontal, // For Grain
  AlignJustify, // For Banding
  Droplets, // For Ink Drop
  ChevronRight,
  ChevronDown, 
  TrendingUp,
  FileWarning,
  Settings,
  Sliders, 
  BookOpen, 
  Scissors, 
  PieChart, 
  BarChart3, 
  FileText, 
  DollarSign,
  Home,
  Layers,
  LayoutGrid,
  Filter,
  MoreHorizontal,
  PauseCircle,
  PlayCircle,
  StopCircle,
  Search,
  CheckSquare,
  Square,
  Share2,
  Flag,
  ScanLine,
  Eraser,
  Palette,
  ArrowLeft
} from 'lucide-react';

export const Icons = {
  Alert: AlertTriangle,
  Printer: Printer,
  Close: X,
  Check: CheckCircle,
  Activity: Activity,
  Maximize: Maximize2,
  Dismiss: EyeOff,
  Restore: Eye,
  Cancel: XCircle,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
  ArrowUp: ArrowUp,
  ArrowLeft: ArrowLeft,
  
  // Defect Types
  Smears: Waves,
  Grain: GripHorizontal,
  Banding: AlignJustify,
  InkDrop: Droplets,
  Scratch: FileWarning,
  Misregistration: Layers,
  Nozzle: Eraser,
  HeadStrike: ScanLine,
  Crease: Waves,
  Contamination: FileWarning,
  Adhesion: Droplets,
  Registration: Layers,
  Color: Palette,
  Palette: Palette,
  
  // UI
  ArrowRight: ChevronRight,
  ChevronDown: ChevronDown,
  Trend: TrendingUp,
  FileDefect: FileWarning,
  Settings: Settings,
  Sliders: Sliders,
  Training: BookOpen,
  Cut: Scissors,
  PieChart: PieChart,
  BarChart: BarChart3,
  FileText: FileText,
  Dollar: DollarSign,
  
  // Navigation & Actions
  Home: Home,
  Jobs: LayoutGrid,
  LayoutGrid: LayoutGrid,
  Filter: Filter,
  More: MoreHorizontal,
  Pause: PauseCircle,
  Play: PlayCircle,
  Stop: StopCircle,
  Search: Search,
  Checkbox: CheckSquare,
  Square: Square,
  Share: Share2,
  Report: Flag
};